### ISSUE TITLE
Next/Prev hrefs link when using ResourceCollection

### ISSUE THREAD

**Issue by rossta** [Fodoj/groovehq#12]
Steps to reproduce:

```ruby
client = Groovehq::Client.new

client.tickets.rels[:next].get
# ArgumentError: bad argument (expected URI object or URI string)
# from /Users/ross/.gem/ruby/2.3.0/gems/httparty-0.13.7/lib/httparty/request.rb:55:in `path='

tickets.rels[:next].href
# => nil
```

**Comment by Fodoj** [comment]
So the problem is that it works only with rels["next"] and not with a symbol?

**Comment by rossta** [comment]
In `Resource#parse_links`, the `Relation` is created from the data assuming `:href` is the key. This works in `Resource` because the `links` variable is created from a `HashWithIndifferentAccess`, but in `ResourceCollection`, `links` is a hash where the `'href'` key is stringified.

**Comment by Fodoj** [comment]
Got it, thanks for explanation
