### ISSUE TITLE
Could not set company_name of customer when creating a new ticket

### ISSUE THREAD

**Issue by dtropp** [Fodoj/groovehq#18]
For example: 
client.create_ticket(from:'dan@cogent.co', to:'support@cogent.co', body: 'test from api', email: 'dan@cogent.co', company_name: 'Cogent Pty Ltd', subject: 'I want this to set company name')

The ticket was created correctly, but the Customer record did get the company name set. I can set the company name with an update_customer() call but I thought the create_ticket() could do it too.

**Comment by dtropp** [comment]
My mistake. I've reread the documentation and I should be passing a hash of Customer attributes in as the :from field. I might submit a PR with an extra spec for this if that's ok.

Love the specs for your gem btw!

**Comment by Fodoj** [comment]
Thanks! I will be happy to review your PR.
