### ISSUE TITLE
going to and from web URLs for tickets

### ISSUE THREAD

**Issue by johnnagro** [Fodoj/groovehq#22]
correct me if i am wrong, but there doesn't seem to be a way to take a URL from the ticket web interface and determine the API ticket ID and visa-versa?

**Comment by Fodoj** [comment]
That's correct, as far as I know

**Comment by johnnagro** [comment]
According to their support team today, you can take an API ticket number and link to it like so:

`https://<portal_name>.groovehq.com/t/<ticket_number>`

And this seems to work for me. I am now trying to get details on going the other way.

**Comment by johnnagro** [comment]
Support got back to me. No way to go in the other direction at this point in time. For my purposes, I will probably just scrape the redirects and keep a lookup table around.
